---
title: "One-way ANOVA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stats) # For linear models
library(MASS) # For random data generation with exact means 
library(knitr) # for nice tables

rm(list = ls())
```


## ANOVA - 3 groups 

```{r anova}
# Parameters
group_size <- 200 
mean_g1 <- 10
mean_g2 <- 12
mean_g3 <- 7
sd_g1 <- 0.3
sd_g2 <- 0.3
sd_g3 <- 0.3 

# Data generation
group_1 <- mvrnorm(n = group_size, mu = mean_g1, Sigma = sd_g1, empirical = TRUE)
group_2 <- mvrnorm(n = group_size, mu = mean_g2, Sigma = sd_g2, empirical = TRUE)
group_3 <- mvrnorm(n = group_size, mu = mean_g3, Sigma = sd_g3, empirical = TRUE)
data <- c(group_1, group_2, group_3)

# Data frame
# Note: if a participant is in group 2, they will receive a 1 for group membership to group 2, and 0 for group membership to group 3 
# Therefore when the linear model is calculated, they will receive the additional score for being in group 2 (group 2 beta * 1) but not group 3 (group 3 beta * 0)
df <- tibble(group_label = rep(c("group_1", "group_2", "group_3"), each = group_size),
             group_n = as_factor(rep(c(0, 1, 2), each = group_size)),
             group_2 = rep(c(0,1,0), each = group_size), 
             group_3 = rep(c(0,0,1), each = group_size),
             y = data)

# Linear model and anova function 
summary(aov(y ~ group_label, data = df))

anova <- summary(lm(formula = y ~ 1 + group_2 + group_3, data = df))

# Output
anova

knitr::kable(coefficients(anova), digits=3)

```

NOTE TO SELF: FIGURE OUT HOW TO DO THIS USING BETAS INSTEAD 

What is a t-test not simply an ANOVA with two groups, or an ANOVA simply a t-test with 3+ groups? 

### Plot ANOVA 

```{r graph_anova}

# Step 1 - standard graph
ggplot(data = df, mapping = aes(x = group_n, y = y)) + 
  geom_point() 

# Step 2 - change axes 
ggplot(data = df, mapping = aes(x = y, y = group_n)) + 
  geom_point() 

# Step 3 - remove regression line 
ggplot(data = df, mapping = aes(x = y, y = group_n)) + 
  geom_point() 

# Step 4 - change colours 
ggplot(data = df, mapping = aes(x = y, y = group_n, color = group_n)) + 
  geom_point(alpha = 0.5) + 
  theme(legend.position = "none")

# Step 5 - move dots from second graph to the x axis 
ggplot(data = df, mapping = aes(x = y, y = 0, color = group_n)) + 
  geom_point(alpha = 0.5) + 
  ylim(0, 1) + 
  theme(legend.position = "none")

# Step 6 - turn into density plots for easier viewing (how t-tests are usually displayed)
ggplot(data = df, aes(x = y, group = group_label, fill = group_label)) + 
  geom_density(alpha = 0.5) 

```
